ALTER TABLE contracts
ADD COLUMN IF NOT EXISTS final_pdf_base64 TEXT,
ADD COLUMN IF NOT EXISTS document_hash TEXT,
ADD COLUMN IF NOT EXISTS qr_code_data_url TEXT,
ADD COLUMN IF NOT EXISTS activated_at TIMESTAMP;
