import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { auth } from "@/lib/auth";
import { sql } from "@/lib/db";

export const dynamic = "force-dynamic";

function formatMoney(value: unknown) {
  return `${Math.round(Number(value ?? 0)).toLocaleString()} ETB`;
}

function formatDate(value: unknown) {
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) return "Not recorded";
  return date.toLocaleString();
}

function writeRow(doc: PDFKit.PDFDocument, label: string, value: string, y: number) {
  doc.fillColor("#6b7280").fontSize(9).text(label.toUpperCase(), 56, y);
  doc.fillColor("#111827").fontSize(11).text(value, 220, y, { width: 310, align: "right" });
}

async function buildPdfBuffer(payment: any) {
  const doc = new PDFDocument({ size: "A4", margin: 56 });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));

  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  doc.fillColor("#111827").fontSize(24).text("DireSkill Payment Receipt");
  doc.moveDown(0.3);
  doc.fillColor("#6b7280").fontSize(10).text("Chapa test-mode payment record");
  doc.moveDown(1.6);

  doc.roundedRect(56, 128, 483, 88, 8).fillAndStroke("#f3f4f6", "#e5e7eb");
  doc.fillColor("#111827").fontSize(12).text(payment.job_title, 76, 150, { width: 280 });
  doc.fillColor("#047857").fontSize(20).text(formatMoney(payment.amount), 360, 146, { width: 150, align: "right" });
  doc.fillColor("#6b7280").fontSize(9).text(String(payment.status).toUpperCase(), 360, 176, { width: 150, align: "right" });

  const startY = 250;
  writeRow(doc, "Receipt ID", payment.payment_id, startY);
  writeRow(doc, "Transaction Ref", payment.chapa_ref || "Not recorded", startY + 28);
  writeRow(doc, "Chapa Status", payment.chapa_status || "Not recorded", startY + 56);
  writeRow(doc, "Created At", formatDate(payment.created_at), startY + 84);
  writeRow(doc, "Client", payment.client_name, startY + 112);
  writeRow(doc, "Worker", payment.worker_name, startY + 140);

  doc.moveTo(56, startY + 184).lineTo(539, startY + 184).strokeColor("#e5e7eb").stroke();
  writeRow(doc, "Total Paid", formatMoney(payment.amount), startY + 210);
  writeRow(doc, "Platform Commission", formatMoney(payment.commission_amount), startY + 238);
  writeRow(doc, "Worker Share", formatMoney(payment.net_amount), startY + 266);

  doc.moveDown(2);
  doc.fillColor("#6b7280").fontSize(9).text(
    "This receipt is generated by DireSkill for Chapa test-mode payment reporting. It is not a tax invoice.",
    56,
    760,
    { width: 483, align: "center" },
  );

  doc.end();
  return done;
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ paymentId: string }> },
) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { paymentId } = await params;
    const rows = await sql`
      SELECT
        p.id as payment_id,
        p.amount,
        p.commission_amount,
        p.net_amount,
        p.status,
        p.chapa_status,
        p.chapa_ref,
        p.created_at,
        j.title as job_title,
        j.client_id,
        j.worker_id,
        COALESCE(cp.full_name, cu.email, 'Client') as client_name,
        COALESCE(wp.full_name, wu.email, 'Worker') as worker_name
      FROM payments p
      JOIN jobs j ON p.job_id = j.id
      JOIN users cu ON j.client_id = cu.id
      JOIN users wu ON j.worker_id = wu.id
      LEFT JOIN client_profiles cp ON cp.user_id = j.client_id
      LEFT JOIN worker_profiles wp ON wp.user_id = j.worker_id
      WHERE p.id = ${paymentId}
      LIMIT 1
    `;

    if (rows.length === 0) {
      return NextResponse.json({ error: "Receipt not found" }, { status: 404 });
    }

    const payment = rows[0];
    const canRead =
      session.user.role === "admin" ||
      session.user.id === payment.client_id ||
      session.user.id === payment.worker_id;

    if (!canRead) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const pdf = await buildPdfBuffer(payment);
    const filename = `direskill-receipt-${payment.chapa_ref || payment.payment_id}.pdf`;

    const body = pdf.buffer.slice(pdf.byteOffset, pdf.byteOffset + pdf.byteLength) as ArrayBuffer;

    return new NextResponse(body, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("[RECEIPT_API_ERROR]", error);
    return NextResponse.json(
      { error: "Failed to generate receipt. Please try again." },
      { status: 500 }
    );
  }
}
